### PR TITLE
Fixed case where operators containing question mark were erroneously substituted by the parameter parser

### LINKED ISSUE #39: Question mark operators interpreted as unnamed parameters
In the following query, the `@?` [JSONB operator](https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-JSONB-OP-TABLE) will be erroneously interpreted by this library as an unnamed parameter. 

```sql
SELECT *
FROM foo
WHERE bar::jsonb @? '$[*].baz' 
```

This library treats the `?` component of the `@?` operator as though it were an unnamed parameter by making this erroneous transformation:

```sql
SELECT *
FROM foo
WHERE bar::jsonb @$1 '$[*].baz' 
```

Note that even though I want to use `@?`, there are also `?|`, `?&` and even bareword `?` JSONB operators. Therefore it may not be sufficient to solve this problem with regex. Perhaps the library should be smarter about doing question mark substitution such that if the statement is not executed with any unnamed parameters, unnamed substitution does not occur. That is, if one wants to use JSONB operators and parameter substitution, they should use named substitution only.

Note further this does not just apply to JSONB. [Geometric functions](https://www.postgresql.org/docs/12/functions-geometry.html) also include a whole other class of operators, many of which contain the question mark. Moreover, extensions are free to implement their own operators that may include question marks too; the same applies to [custom operators](https://www.postgresql.org/docs/current/sql-createoperator.html).

## Solutions

1. Improve the regex to exclude most operators
2. Implicitly ignore question mark placeholders when no numeric keys specified
3. Explicitly ignore question mark placeholders
4. Add an escape sequence for question marks

### Improve the regex to exclude most operators
Considering operators may include the following characters, `` + - * / < > = ~ ! @ # % ^ & | ` ?``, the regex can be extended to exclude question marks surrounded by these other characters. This does not interfere with normal usage, such as `INSERT INTO foo VALUES (?, ?)`, where question marks are typically only surrounded by braces, commas and whitespace, which are not valid operator characters. However, this solution would never be able to handle the bare question mark case (`?`).

### Implicitly ignore question mark placeholders when no numeric keys specified
If we assume when that when no parameters are specified with numeric keys, we can safely disable question mark substitution, this could be an elegant and implicit way to avoid the problem in some cases.

### Explicitly ignore question mark placeholders
Similar to above, we could add an explicit option to disable question mark placeholders. This is the approach taken by some other client libraries such as [DBD::Pg](https://metacpan.org/pod/DBD::Pg#Placeholders).

### Add an escape sequence for question marks
Allowing question marks to be escaped makes it clear they are not to be used as placeholders. 

```sql
WHERE bar::jsonb @\? '$[*].baz' 
```

This approach also supports the bare question mark case. However, the a weakness to this approach is it makes the query less portable (e.g. pasting into another program to test).

A combination of these solutions may also be feasible. For example, improving the regex and also implementing the escape just for the bare question mark case.

### PR DESCRIPTION
**Pull request by Bilge**
Fixes #39.

### CODE REVIEW

File: test/InternalFunctionsTest.php [hunk 1]
```diff
@@ -9,16 +9,53 @@
...
+        self::assertSame($sqlOut, parseNamedParams($sqlIn, $dummy));
+    }
+
+    public function provideUnnamedParams(): iterable
+    {
+        return [
+            'Bare' => ['SELECT ?', 'SELECT $1'],
+            'Parenthesized' => ['SELECT (?)', 'SELECT ($1)'],
+            'Row constructor' => ['SELECT (?, ?)', 'SELECT ($1, $2)'],
+        ];
```
Comment (kelunik) [inline test/InternalFunctionsTest.php:28]: Hint: Yield could be used here, but I think there's no need yet for readability.

File: test/InternalFunctionsTest.php [hunk 2]
```diff
@@ -9,16 +9,53 @@
...
+    /**
+     * Tests that operators containing the question mark character, that could be confused with unnamed parameters,
+     * are parsed correctly.
      *
      * @see parseNamedParams
      * @see https://github.com/amphp/postgres/issues/39
+     * @dataProvider provideProblematicOperators
      */
-    public function testParseJsonbOperator(): void
+    public function testParseProblematicOperators(string $sql): void
```
Comment (kelunik) [inline test/InternalFunctionsTest.php:39]: I think the test cases can be merged into one test method, as the problematic ones shouldn't be problematic after the fix.

Comment (Bilge) [reply test/InternalFunctionsTest.php:39]: For what benefit? Two distinct sets is clearer.

Comment (kelunik) [reply test/InternalFunctionsTest.php:39]: Better overview, after all it's one test-set that needs to work.

Comment (Bilge) [reply test/InternalFunctionsTest.php:39]: I cannot see the benefit of combining test cases that perform substitutions with test cases that do not. They are complete opposites. As such it would be unconscionable for me to make such a change, but obviously you can still make whatever changes you want after merging since it is your project.

**Comment by trowski** [comment]
@Bilge I get several tests failing due to the regex not providing the matches expected.
